export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const CARD_ITEMS = 'CARD_ITEMS';

//NOTIFICATION Errors 
export const NOTIFICATION_ERROR = "NOTIFICATION_ERROR";

//NOTIFICATION SUCCESS
export const NOTIFICATION_SUCCESS = "NOTIFICATION_SUCCESS";

//NOTIFICATION WARNING
export const NOTIFICATION_WARNING = "NOTIFICATION_WARNING";

//NOTIFICATION INFO
export const NOTIFICATION_INFO = "NOTIFICATION_INFO";