export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const CARD_ITEMS = 'CARD_ITEMS';

//NOTIFICATION ERRORS 
export const NOTIFICATION_ERROR = "NOTIFICATION_ERROR";

//NOTIFICATION SUCCESS
export const NOTIFICATION_SUCCESS = "NOTIFICATION_SUCCESS";

//NOTIFICATION WARNING
export const NOTIFICATION_WARNING = "NOTIFICATION_WARNING";

//NOTIFICATION INFO
export const NOTIFICATION_INFO = "NOTIFICATION_INFO";

//GEO INFO
export const GEO_INFO = "GEO_INFO";

//LOADING
export const LOADING = "LOADING";

//LOGIN ERRORS
export const LOG_ERRORS = "LOG_ERRORS";

//PRODUCTS
export const PRODUCTS = "PRODUCTS";

//SIZE
export const SIZE = "SIZE";

//COLOR
export const COLOR = "COLOR";

